<?xml version="1.0"?>
  <robot xmlns:xacro="http://wiki.ros.org/xacro" name="myur5">

  <!--<xacro:include filename="$(find myur5_description)/urdf/myur5.gazebo" />
  <xacro:include filename="$(find myur5_description)/urdf/materials.xacro" />-->


  <xacro:include filename="$(find ur_gazebo)/urdf/ur_macro.xacro"/>
  <xacro:include filename="$(find ur_description)/urdf/inc/ur5_macro.xacro"/>

  <xacro:property name="pedestal_base_height" value="0.83"/>
  <xacro:property name="pedestal_base_width" value="0.07"/>

  <xacro:property name="pedestal_connector_width" value="0.165"/>
  <xacro:property name="pedestal_connector_height" value="0.013"/>

  <link name="world"/>

  <link name="pedestal_base">
    <inertial>
      <origin xyz="0 0 ${pedestal_base_height/2}" rpy="0 0 0"/>
      <mass value="20"/>
      <inertia ixx="200" ixy="200" ixz="200" iyy="200" iyz="200" izz="200"/>
    </inertial>
    <visual>
      <origin xyz="0 0 ${pedestal_base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${pedestal_base_width} ${pedestal_base_width} ${pedestal_base_height}"/>
      </geometry>
      <material name="Gray">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 ${pedestal_base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${pedestal_base_width} ${pedestal_base_width} ${pedestal_base_height}"/>
      </geometry>
    </collision>
  </link>

  <link name="pedestal_connector">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="20"/>
      <inertia ixx="200" ixy="200" ixz="200" iyy="200" iyz="200" izz="200"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${pedestal_connector_width} ${pedestal_connector_width} ${pedestal_connector_height}"/>
      </geometry>
      <material name="Gray">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${pedestal_connector_width} ${pedestal_connector_width} ${pedestal_connector_height}"/>
      </geometry>
    </collision>
  </link>

  <xacro:ur5_robot prefix="" />

  <joint name="world_joint" type="fixed">
    <parent link="world" />
    <child link="pedestal_base" />
    <origin xyz="0 0 0" rpy="0.0 0.0 0.0"/>
  </joint>

  <joint name="pedestal_joint" type="fixed">
    <parent link="pedestal_base" />
    <child link="pedestal_connector" />
    <origin xyz="0 0 ${pedestal_base_height}" rpy="0.0 0.0 0.0"/>
  </joint>

  <joint name="base_joint" type="fixed">
    <parent link="pedestal_connector" />
    <child link="base_link" />
    <origin xyz="0 0 ${pedestal_connector_height/2}" rpy="0.0 0.0 0.0"/>
  </joint>
	
</robot>
